[project]
name = "guardrail-enforcement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic[bedrock]>=0.120.2",
    "boto3>=1.43.62",
    "openai>=2.52.0",
    "python-dotenv>=1.2.2",
    "strands-agents>=1.50.2",
]
